const $=s=>document.querySelector(s);
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('#'+v).classList.add('active');if(v==='paste')loadPastes();if(v==='files')loadFiles();}
function fmt(s){if(s<=0)return'expired';let h=Math.floor(s/3600),m=Math.floor((s%3600)/60);if(h>=24)return Math.floor(h/24)+'d '+h%24+'h';return h?h+'h '+m+'m':m+'m';}
async function createPaste(){let t=$('#pasteText').value;if(!t.trim())return;let r=await fetch('/api/paste',{method:'POST',body:t});let j=await r.json();if(!r.ok){$('#pasteStatus').textContent=j.error||'failed';return}$('#pasteText').value='';$('#pasteStatus').textContent='Created';loadPastes();}
async function loadPastes(){let r=await fetch('/api/pastes');if(!r.ok)return;let j=await r.json();let box=$('#pastes');box.innerHTML=j.items.length?'':'<div class="empty">No active pastes.</div>';j.items.forEach(x=>{let d=document.createElement('div');d.className='item';d.innerHTML=`<div class="preview">${esc(x.preview)}</div><div class="meta"><span>${new Date(x.created_at*1000).toLocaleString()}</span><span>${esc(x.remaining)} left</span></div>`;d.onclick=()=>openPaste(x.id);box.appendChild(d);});}
async function openPaste(id){let r=await fetch('/api/paste/'+id);let j=await r.json();if(r.ok){$('#pasteText').value=j.content;$('#pasteText').focus();}}
function dropFiles(e){e.preventDefault();$('#drop').classList.remove('drag');uploadFiles(e.dataTransfer.files);}
async function uploadFiles(files){for(const f of files){let fd=new FormData();fd.append('file',f);$('#fileStatus').textContent='Uploading '+f.name+'…';let r=await fetch('/api/files',{method:'POST',body:fd});let j=await r.json();if(!r.ok)alert(f.name+': '+(j.error||'upload failed'));}$('#fileStatus').textContent='';loadFiles();}
async function loadFiles(){let r=await fetch('/api/files');if(!r.ok)return;let j=await r.json();let box=$('#filesList');box.innerHTML=j.items.length?'':'<div class="empty">No active files.</div>';j.items.forEach(x=>{let d=document.createElement('div');d.className='item file-row';d.innerHTML=`<div class="file-name">${esc(x.name)}</div><small>${(x.size/1048576).toFixed(2)} MB</small><small>${esc(x.remaining)} left</small><a href="${encodeURI(x.url)}" download>Download</a>`;box.appendChild(d);});}
function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
loadPastes();
